// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/gndw/starting-golang/internals/constants"
	mock "github.com/stretchr/testify/mock"
)

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// RegisterEndpoint provides a mock function for the type Service
func (_mock *Service) RegisterEndpoint(ctx context.Context, method string, path string, f constants.HttpFunction) error {
	ret := _mock.Called(ctx, method, path, f)

	if len(ret) == 0 {
		panic("no return value specified for RegisterEndpoint")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, constants.HttpFunction) error); ok {
		r0 = returnFunc(ctx, method, path, f)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_RegisterEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterEndpoint'
type Service_RegisterEndpoint_Call struct {
	*mock.Call
}

// RegisterEndpoint is a helper method to define mock.On call
//   - ctx context.Context
//   - method string
//   - path string
//   - f constants.HttpFunction
func (_e *Service_Expecter) RegisterEndpoint(ctx interface{}, method interface{}, path interface{}, f interface{}) *Service_RegisterEndpoint_Call {
	return &Service_RegisterEndpoint_Call{Call: _e.mock.On("RegisterEndpoint", ctx, method, path, f)}
}

func (_c *Service_RegisterEndpoint_Call) Run(run func(ctx context.Context, method string, path string, f constants.HttpFunction)) *Service_RegisterEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 constants.HttpFunction
		if args[3] != nil {
			arg3 = args[3].(constants.HttpFunction)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Service_RegisterEndpoint_Call) Return(err error) *Service_RegisterEndpoint_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_RegisterEndpoint_Call) RunAndReturn(run func(ctx context.Context, method string, path string, f constants.HttpFunction) error) *Service_RegisterEndpoint_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type Service
func (_mock *Service) Shutdown(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type Service_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Service_Expecter) Shutdown(ctx interface{}) *Service_Shutdown_Call {
	return &Service_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *Service_Shutdown_Call) Run(run func(ctx context.Context)) *Service_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Service_Shutdown_Call) Return(err error) *Service_Shutdown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_Shutdown_Call) RunAndReturn(run func(ctx context.Context) error) *Service_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type Service
func (_mock *Service) Start(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type Service_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Service_Expecter) Start(ctx interface{}) *Service_Start_Call {
	return &Service_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *Service_Start_Call) Run(run func(ctx context.Context)) *Service_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Service_Start_Call) Return(err error) *Service_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_Start_Call) RunAndReturn(run func(ctx context.Context) error) *Service_Start_Call {
	_c.Call.Return(run)
	return _c
}
