// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewDependency creates a new instance of Dependency. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDependency(t interface {
	mock.TestingT
	Cleanup(func())
}) *Dependency {
	mock := &Dependency{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Dependency is an autogenerated mock type for the Dependency type
type Dependency struct {
	mock.Mock
}

type Dependency_Expecter struct {
	mock *mock.Mock
}

func (_m *Dependency) EXPECT() *Dependency_Expecter {
	return &Dependency_Expecter{mock: &_m.Mock}
}

// Load provides a mock function for the type Dependency
func (_mock *Dependency) Load(filenames ...string) error {
	var tmpRet mock.Arguments
	if len(filenames) > 0 {
		tmpRet = _mock.Called(filenames)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(...string) error); ok {
		r0 = returnFunc(filenames...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Dependency_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type Dependency_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - filenames ...string
func (_e *Dependency_Expecter) Load(filenames ...interface{}) *Dependency_Load_Call {
	return &Dependency_Load_Call{Call: _e.mock.On("Load",
		append([]interface{}{}, filenames...)...)}
}

func (_c *Dependency_Load_Call) Run(run func(filenames ...string)) *Dependency_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		var variadicArgs []string
		if len(args) > 0 {
			variadicArgs = args[0].([]string)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *Dependency_Load_Call) Return(err error) *Dependency_Load_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Dependency_Load_Call) RunAndReturn(run func(filenames ...string) error) *Dependency_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Overload provides a mock function for the type Dependency
func (_mock *Dependency) Overload(filenames ...string) error {
	var tmpRet mock.Arguments
	if len(filenames) > 0 {
		tmpRet = _mock.Called(filenames)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Overload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(...string) error); ok {
		r0 = returnFunc(filenames...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Dependency_Overload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Overload'
type Dependency_Overload_Call struct {
	*mock.Call
}

// Overload is a helper method to define mock.On call
//   - filenames ...string
func (_e *Dependency_Expecter) Overload(filenames ...interface{}) *Dependency_Overload_Call {
	return &Dependency_Overload_Call{Call: _e.mock.On("Overload",
		append([]interface{}{}, filenames...)...)}
}

func (_c *Dependency_Overload_Call) Run(run func(filenames ...string)) *Dependency_Overload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		var variadicArgs []string
		if len(args) > 0 {
			variadicArgs = args[0].([]string)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *Dependency_Overload_Call) Return(err error) *Dependency_Overload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Dependency_Overload_Call) RunAndReturn(run func(filenames ...string) error) *Dependency_Overload_Call {
	_c.Call.Return(run)
	return _c
}
