// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"io"

	"github.com/gndw/starting-golang/internals/dependencies/slog"
	mock "github.com/stretchr/testify/mock"
)

// NewDependency creates a new instance of Dependency. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDependency(t interface {
	mock.TestingT
	Cleanup(func())
}) *Dependency {
	mock := &Dependency{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Dependency is an autogenerated mock type for the Dependency type
type Dependency struct {
	mock.Mock
}

type Dependency_Expecter struct {
	mock *mock.Mock
}

func (_m *Dependency) EXPECT() *Dependency_Expecter {
	return &Dependency_Expecter{mock: &_m.Mock}
}

// NewJSONLogger provides a mock function for the type Dependency
func (_mock *Dependency) NewJSONLogger(w io.Writer) slog.Logger {
	ret := _mock.Called(w)

	if len(ret) == 0 {
		panic("no return value specified for NewJSONLogger")
	}

	var r0 slog.Logger
	if returnFunc, ok := ret.Get(0).(func(io.Writer) slog.Logger); ok {
		r0 = returnFunc(w)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(slog.Logger)
		}
	}
	return r0
}

// Dependency_NewJSONLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewJSONLogger'
type Dependency_NewJSONLogger_Call struct {
	*mock.Call
}

// NewJSONLogger is a helper method to define mock.On call
//   - w io.Writer
func (_e *Dependency_Expecter) NewJSONLogger(w interface{}) *Dependency_NewJSONLogger_Call {
	return &Dependency_NewJSONLogger_Call{Call: _e.mock.On("NewJSONLogger", w)}
}

func (_c *Dependency_NewJSONLogger_Call) Run(run func(w io.Writer)) *Dependency_NewJSONLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 io.Writer
		if args[0] != nil {
			arg0 = args[0].(io.Writer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Dependency_NewJSONLogger_Call) Return(logger slog.Logger) *Dependency_NewJSONLogger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *Dependency_NewJSONLogger_Call) RunAndReturn(run func(w io.Writer) slog.Logger) *Dependency_NewJSONLogger_Call {
	_c.Call.Return(run)
	return _c
}
