// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewLogger creates a new instance of Logger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *Logger {
	mock := &Logger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

type Logger_Expecter struct {
	mock *mock.Mock
}

func (_m *Logger) EXPECT() *Logger_Expecter {
	return &Logger_Expecter{mock: &_m.Mock}
}

// DebugContext provides a mock function for the type Logger
func (_mock *Logger) DebugContext(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// Logger_DebugContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DebugContext'
type Logger_DebugContext_Call struct {
	*mock.Call
}

// DebugContext is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *Logger_Expecter) DebugContext(ctx interface{}, msg interface{}, args ...interface{}) *Logger_DebugContext_Call {
	return &Logger_DebugContext_Call{Call: _e.mock.On("DebugContext",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *Logger_DebugContext_Call) Run(run func(ctx context.Context, msg string, args ...any)) *Logger_DebugContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Logger_DebugContext_Call) Return() *Logger_DebugContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *Logger_DebugContext_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *Logger_DebugContext_Call {
	_c.Run(run)
	return _c
}

// ErrorContext provides a mock function for the type Logger
func (_mock *Logger) ErrorContext(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// Logger_ErrorContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ErrorContext'
type Logger_ErrorContext_Call struct {
	*mock.Call
}

// ErrorContext is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *Logger_Expecter) ErrorContext(ctx interface{}, msg interface{}, args ...interface{}) *Logger_ErrorContext_Call {
	return &Logger_ErrorContext_Call{Call: _e.mock.On("ErrorContext",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *Logger_ErrorContext_Call) Run(run func(ctx context.Context, msg string, args ...any)) *Logger_ErrorContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Logger_ErrorContext_Call) Return() *Logger_ErrorContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *Logger_ErrorContext_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *Logger_ErrorContext_Call {
	_c.Run(run)
	return _c
}

// InfoContext provides a mock function for the type Logger
func (_mock *Logger) InfoContext(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// Logger_InfoContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InfoContext'
type Logger_InfoContext_Call struct {
	*mock.Call
}

// InfoContext is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *Logger_Expecter) InfoContext(ctx interface{}, msg interface{}, args ...interface{}) *Logger_InfoContext_Call {
	return &Logger_InfoContext_Call{Call: _e.mock.On("InfoContext",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *Logger_InfoContext_Call) Run(run func(ctx context.Context, msg string, args ...any)) *Logger_InfoContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Logger_InfoContext_Call) Return() *Logger_InfoContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *Logger_InfoContext_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *Logger_InfoContext_Call {
	_c.Run(run)
	return _c
}

// WarnContext provides a mock function for the type Logger
func (_mock *Logger) WarnContext(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// Logger_WarnContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WarnContext'
type Logger_WarnContext_Call struct {
	*mock.Call
}

// WarnContext is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *Logger_Expecter) WarnContext(ctx interface{}, msg interface{}, args ...interface{}) *Logger_WarnContext_Call {
	return &Logger_WarnContext_Call{Call: _e.mock.On("WarnContext",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *Logger_WarnContext_Call) Run(run func(ctx context.Context, msg string, args ...any)) *Logger_WarnContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Logger_WarnContext_Call) Return() *Logger_WarnContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *Logger_WarnContext_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *Logger_WarnContext_Call {
	_c.Run(run)
	return _c
}
