// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	context "context"
	models "github.com/gndw/starting-golang/internals/models"

	mock "github.com/stretchr/testify/mock"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// Test provides a mock function with given fields: ctx, request
func (_m *Usecase) Test(ctx context.Context, request models.TestRequest) (models.TestResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Test")
	}

	var r0 models.TestResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.TestRequest) (models.TestResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.TestRequest) models.TestResponse); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(models.TestResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.TestRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUsecase creates a new instance of Usecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *Usecase {
	mock := &Usecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
