// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/gndw/starting-golang/internals/models"
	mock "github.com/stretchr/testify/mock"
)

// NewUsecase creates a new instance of Usecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *Usecase {
	mock := &Usecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

type Usecase_Expecter struct {
	mock *mock.Mock
}

func (_m *Usecase) EXPECT() *Usecase_Expecter {
	return &Usecase_Expecter{mock: &_m.Mock}
}

// Test provides a mock function for the type Usecase
func (_mock *Usecase) Test(ctx context.Context, request models.TestRequest) (models.TestResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Test")
	}

	var r0 models.TestResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.TestRequest) (models.TestResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.TestRequest) models.TestResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(models.TestResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.TestRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Usecase_Test_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Test'
type Usecase_Test_Call struct {
	*mock.Call
}

// Test is a helper method to define mock.On call
//   - ctx context.Context
//   - request models.TestRequest
func (_e *Usecase_Expecter) Test(ctx interface{}, request interface{}) *Usecase_Test_Call {
	return &Usecase_Test_Call{Call: _e.mock.On("Test", ctx, request)}
}

func (_c *Usecase_Test_Call) Run(run func(ctx context.Context, request models.TestRequest)) *Usecase_Test_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.TestRequest
		if args[1] != nil {
			arg1 = args[1].(models.TestRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Usecase_Test_Call) Return(response models.TestResponse, err error) *Usecase_Test_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *Usecase_Test_Call) RunAndReturn(run func(ctx context.Context, request models.TestRequest) (models.TestResponse, error)) *Usecase_Test_Call {
	_c.Call.Return(run)
	return _c
}
