// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"io"
	"io/fs"

	mock "github.com/stretchr/testify/mock"
)

// NewDependency creates a new instance of Dependency. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDependency(t interface {
	mock.TestingT
	Cleanup(func())
}) *Dependency {
	mock := &Dependency{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Dependency is an autogenerated mock type for the Dependency type
type Dependency struct {
	mock.Mock
}

type Dependency_Expecter struct {
	mock *mock.Mock
}

func (_m *Dependency) EXPECT() *Dependency_Expecter {
	return &Dependency_Expecter{mock: &_m.Mock}
}

// Exit provides a mock function for the type Dependency
func (_mock *Dependency) Exit(code int) {
	_mock.Called(code)
	return
}

// Dependency_Exit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exit'
type Dependency_Exit_Call struct {
	*mock.Call
}

// Exit is a helper method to define mock.On call
//   - code int
func (_e *Dependency_Expecter) Exit(code interface{}) *Dependency_Exit_Call {
	return &Dependency_Exit_Call{Call: _e.mock.On("Exit", code)}
}

func (_c *Dependency_Exit_Call) Run(run func(code int)) *Dependency_Exit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Dependency_Exit_Call) Return() *Dependency_Exit_Call {
	_c.Call.Return()
	return _c
}

func (_c *Dependency_Exit_Call) RunAndReturn(run func(code int)) *Dependency_Exit_Call {
	_c.Run(run)
	return _c
}

// Getenv provides a mock function for the type Dependency
func (_mock *Dependency) Getenv(key string) string {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Getenv")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Dependency_Getenv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Getenv'
type Dependency_Getenv_Call struct {
	*mock.Call
}

// Getenv is a helper method to define mock.On call
//   - key string
func (_e *Dependency_Expecter) Getenv(key interface{}) *Dependency_Getenv_Call {
	return &Dependency_Getenv_Call{Call: _e.mock.On("Getenv", key)}
}

func (_c *Dependency_Getenv_Call) Run(run func(key string)) *Dependency_Getenv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Dependency_Getenv_Call) Return(s string) *Dependency_Getenv_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Dependency_Getenv_Call) RunAndReturn(run func(key string) string) *Dependency_Getenv_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function for the type Dependency
func (_mock *Dependency) Stat(name string) (fs.FileInfo, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 fs.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (fs.FileInfo, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) fs.FileInfo); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Dependency_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type Dependency_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - name string
func (_e *Dependency_Expecter) Stat(name interface{}) *Dependency_Stat_Call {
	return &Dependency_Stat_Call{Call: _e.mock.On("Stat", name)}
}

func (_c *Dependency_Stat_Call) Run(run func(name string)) *Dependency_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Dependency_Stat_Call) Return(fileInfo fs.FileInfo, err error) *Dependency_Stat_Call {
	_c.Call.Return(fileInfo, err)
	return _c
}

func (_c *Dependency_Stat_Call) RunAndReturn(run func(name string) (fs.FileInfo, error)) *Dependency_Stat_Call {
	_c.Call.Return(run)
	return _c
}

// Stdout provides a mock function for the type Dependency
func (_mock *Dependency) Stdout() io.Writer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stdout")
	}

	var r0 io.Writer
	if returnFunc, ok := ret.Get(0).(func() io.Writer); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Writer)
		}
	}
	return r0
}

// Dependency_Stdout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stdout'
type Dependency_Stdout_Call struct {
	*mock.Call
}

// Stdout is a helper method to define mock.On call
func (_e *Dependency_Expecter) Stdout() *Dependency_Stdout_Call {
	return &Dependency_Stdout_Call{Call: _e.mock.On("Stdout")}
}

func (_c *Dependency_Stdout_Call) Run(run func()) *Dependency_Stdout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Dependency_Stdout_Call) Return(writer io.Writer) *Dependency_Stdout_Call {
	_c.Call.Return(writer)
	return _c
}

func (_c *Dependency_Stdout_Call) RunAndReturn(run func() io.Writer) *Dependency_Stdout_Call {
	_c.Call.Return(run)
	return _c
}
