// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// Info provides a mock function for the type Service
func (_mock *Service) Info(ctx context.Context, format string, a ...any) {
	if len(a) > 0 {
		_mock.Called(ctx, format, a)
	} else {
		_mock.Called(ctx, format)
	}

	return
}

// Service_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type Service_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - ctx context.Context
//   - format string
//   - a ...any
func (_e *Service_Expecter) Info(ctx interface{}, format interface{}, a ...interface{}) *Service_Info_Call {
	return &Service_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{ctx, format}, a...)...)}
}

func (_c *Service_Info_Call) Run(run func(ctx context.Context, format string, a ...any)) *Service_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Service_Info_Call) Return() *Service_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *Service_Info_Call) RunAndReturn(run func(ctx context.Context, format string, a ...any)) *Service_Info_Call {
	_c.Run(run)
	return _c
}
